spring.application.name=TP1Guilda

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.default_schema=audit
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true